image: docker:latest

services:
  - name: docker:dind
    alias: docker
    command: ["--dns=8.8.8.8"]  # Use Google's DNS

variables:
  DOCKER_TLS_CERTDIR: ""  # Disable TLS since we're using DinD
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_DRIVER: overlay2
  # These are needed for buildx
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  FF_NETWORK_PER_BUILD: "true"  # Use a clean network for each job

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache bash
  # Create .env.production from GitLab variables
  - |
    cat > .env.production << EOF
    NODE_ENV=production
    PORT=3050
    HOSTNAME=0.0.0.0
    MONGODB_URI=mongodb://admin:${DB_PASSWORD}@mongodb:27017/darkflows?authSource=admin
    NEXT_TELEMETRY_DISABLED=1
    JWT_SECRET=${JWT_SECRET}
    RESET_PASSWORD=${RESET_PASSWORD}
    NEXT_PUBLIC_APP_URL=https://darkflows.com
    EOF
  # Set up buildx
  - docker buildx create --use --driver docker-container

build:
  stage: build
  script:
    - chmod +x ./build.sh
    - ./build.sh
  only:
    - main

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - ./deploy.sh --prod
  only:
    - main 