image: docker:24.0.7

services:
  - name: docker:24.0.7-dind
    alias: dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

variables:
  DOCKER_HOST: "tcp://dind:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: "overlay2"

stages:
  - build
  - notify

build:
  stage: build
  before_script:
    - apk add --no-cache bash
  script:
    - apk add --no-cache drill
    - echo "Testing DNS for 'dind':"
    - drill dind
    - pwd
    - docker version
    - docker info
    - docker ps
    - chmod +x build.sh  # Ensure the script is executable
    - bash ./build.sh
  only:
    - main

notify:
  stage: notify
  script:
    - curl -X POST "https://darkflows.com/deploy?token=${DEPLOY_TOKEN}"
  only:
    - main
