image: docker:latest

services:
  - name: docker:dind
    alias: docker

variables:
  # Use Docker socket instead of TCP
  DOCKER_HOST: ""
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache bash
  # Create .env.production from GitLab variables
  - |
    cat > .env.production << EOF
    NODE_ENV=production
    PORT=3050
    HOSTNAME=0.0.0.0
    MONGODB_URI=mongodb://admin:${DB_PASSWORD}@mongodb:27017/darkflows?authSource=admin
    NEXT_TELEMETRY_DISABLED=1
    JWT_SECRET=${JWT_SECRET}
    RESET_PASSWORD=${RESET_PASSWORD}
    NEXT_PUBLIC_APP_URL=https://darkflows.com
    EOF
  # Set up buildx
  - docker buildx create --name mybuilder --use

build:
  stage: build
  script:
    - chmod +x ./build.sh
    - ./build.sh
  only:
    - main

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - ./deploy.sh --prod
  only:
    - main 