image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache bash
  # Create .env.production from GitLab variables
  - |
    cat > .env.production << EOF
    NODE_ENV=production
    PORT=3050
    HOSTNAME=0.0.0.0
    MONGODB_URI=mongodb://admin:${DB_PASSWORD}@mongodb:27017/darkflows?authSource=admin
    NEXT_TELEMETRY_DISABLED=1
    JWT_SECRET=${JWT_SECRET}
    RESET_PASSWORD=${RESET_PASSWORD}
    NEXT_PUBLIC_APP_URL=https://darkflows.com
    EOF

build:
  stage: build
  script:
    - chmod +x ./build.sh
    - ./build.sh
  only:
    - main

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - ./deploy.sh --prod
  only:
    - main 