stages:
  - build
  - notify

build:
  stage: build
  script:
    - chmod +x ./build.sh
    - ./build.sh
  only:
    - main

notify:
  stage: notify
  script:
    - 'curl -X POST "https://darkflows.com/deploy?token=${DEPLOY_TOKEN}"'
  only:
    - main 