stages:
  - build
  - notify

build:
  stage: build
  before_script:
    - apk add --no-cache bash
  script:
    - pwd
    - ls -la
    - bash ./build.sh
  only:
    - main

notify:
  stage: notify
  script:
    - 'curl -X POST "https://darkflows.com/deploy?token=${DEPLOY_TOKEN}"'
  only:
    - main 