version: '3.8'

services:
  darkflows:
    container_name: darkflows
    image: proggod/darkflows-web:latest
    ports:
      - "3050:3050"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - mongodb
    volumes:
      - uploads_data:/app/public/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/api/debug"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:darkflows@mongodb:27017/darkflows?authSource=admin
      - RESET_PASSWORD=${RESET_PASSWORD}
      - NEXTAUTH_URL=https://darkflows.com  # Replace with your actual domain
      - NEXTAUTH_URL_INTERNAL=http://localhost:3050
      - NEXT_PUBLIC_APP_URL=https://darkflows.com  # Replace with your actual domain

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=darkflows
    volumes:
      - /var/www/darkflows.com/data/db:/data/db
    networks:
      - web
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads_data:
    driver: local
    driver_opts:
      type: none
      device: /var/www/darkflows.com/public/uploads
      o: bind

networks:
  web:
    driver: bridge 