services:
  darkflows:
    container_name: darkflows-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3050:3050"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next-cache:/app/.next
      - ./public/uploads:/uploads
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=development
      - PORT=3050
      - NEXT_TELEMETRY_DISABLED=1
      - JWT_SECRET=${JWT_SECRET}
      - RESET_PASSWORD=${RESET_PASSWORD}
      - NEXT_PUBLIC_APP_URL=http://localhost:3050
      - UPLOADS_PATH=/uploads
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: darkflows-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=darkflows
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=darkflows
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data_dev:
  node_modules:
  next-cache:
  uploads_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/public/uploads
      o: bind 