version: '3.8'

services:
  darkflows:
    container_name: darkflows
    image: proggod/darkflows-web:latest
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - PORT=3050
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - web
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3050"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true

networks:
  web:
    driver: bridge 