version: '3.8'

services:
  darkflows:
    container_name: darkflows-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=development
    restart: unless-stopped 