version: '3.8'

services:
  darkflows:
    container_name: darkflows-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    env_file:
      - .env.development
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  mongodb:
    image: mongo:latest
    container_name: darkflows-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=darkflows

volumes:
  mongodb_data: 