version: '3'

services:
  darkflows:
    container_name: darkflows
    image: proggod/darkflows-web:latest
    # For local development, you can build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: co2_emissions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 