services:
  darkflows:
    container_name: darkflows
    image: proggod/darkflows-web:latest
    # For local development, you can build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=gfgd09809fd8g90dfg8df09g8gdf098g098
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - ./public/uploads:/uploads

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: darkflows
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: darkflows
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data: 