version: '3.8'

services:
  darkflows:
    container_name: darkflows
    image: proggod/darkflows-web:latest
    ports:
      - "3050:3050"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - mongodb
    volumes:
      - /var/www/darkflows.com/public/uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3050"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:darkflows@mongodb:27018/darkflows?authSource=admin

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=darkflows
    ports:
      - "27018:27017"
    volumes:
      - /var/www/darkflows.com/data/db:/data/db
    networks:
      - web
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads_data:
    driver: local

networks:
  web:
    driver: bridge 